<a href="https://colab.research.google.com/github/katha815/ADME-Classifier/blob/main/Compare_CData_with_Orginial_SNVs.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).

In [ ]:
# Read the three datasets
core = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/Core.csv")
extended = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/Extended.csv")
others = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/Others.csv")

# Add a column indicating the source dataset
core['Dataset'] = 'Core'
extended['Dataset'] = 'Extended'
others['Dataset'] = 'Others'

# Merge the datasets into one
comparison = pd.concat([core, extended, others], ignore_index=True)

# Rename the merged dataset to "Comparison"
comparison.name = "Comparison"
comparison

,Unnamed: 0,Chromosome,Genes,Location,Reference Base,Altered Base,numeric,Literature,Drugs,Association,More Details,Dataset
0,206,10,ABCC2,99861014,C,G,1,PMID:18294295,docetaxel,Allele G is associated with increased risk of ...,Study genotyped 84 patients from BioBank Japan...,Core
1,135,10,ABCC2,99852563,C,T,1,PMID:27180762,vincristine,Allele T is associated with decreased likeliho...,when comparing zero neurotoxicity vs grades 1-...,Core
2,34,10,ABCC2,99843765,T,C,1,PMID:30100615,rosuvastatin,Allele C is associated with decreased exposure...,NaN,Core
3,46,10,ABCC2,99804028,C,T,1,PMID:30100615,rosuvastatin,Allele T is associated with decreased exposure...,NaN,Core
4,37,10,ABCC2,99804266,C,T,0,PMID:21449672,antiepileptics,Allele C is not associated with resistance to ...,Epilepsy patients on antiepileptic drug (AED) ...,Core
...,...,...,...,...,...,...,...,...,...,...,...,...
364,9,4,SLC2A9,9961141,T,C,0,PMCID:PMC5611711,furosemide,Allele C is not associated with response to fu...,There was no difference in either the absolute...,Others
365,10,4,SLC2A9,9920543,C,T,1,PMCID:PMC2779583,NaN,Allele T is associated with decreased serum ur...,"The first part of this study was a GWAS, the f...",Others
366,5,8,DPYS,104451462,A,G,0,PMCID:PMC3694243,capecitabine; fluorouracil,Allele A is not associated with risk of Drug T...,No significant differences in occurrence of gr...,Others
367,1,8,DPYS,104466921,A,G,1,PMID:26244261,fluorouracil,Allele G is associated with increased likeliho...,This was a trend in the discovery cohort but s...,Others
368,6,8,DPYS,104424265,C,T,0,PMID:26244261,fluorouracil,Allele T is associated with increased likeliho...,This novel rare allele was found in an individ...,Others

In [ ]:
# Read the "337SNVs" dataset
snvs = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/337SNVs.csv")

# Add a column to store the check result
comparison['Check Result'] = comparison.apply(lambda row: snvs.loc[
    (snvs['chr'] == row['Chromosome']) & (snvs['Location'] == row['Location']), 'Alter'].values[0]
    if ((snvs['chr'] == row['Chromosome']) & (snvs['Location'] == row['Location'])).any()
    else '', axis=1)
# Check if the alter from old dataset matches with the comparison dataset
comparison['Alter Match'] = comparison.apply(lambda row: snvs.loc[
    (snvs['chr'] == row['Chromosome']) & (snvs['Location'] == row['Location']), 'Alter'].values[0] == row['Check Result']
    if ((snvs['chr'] == row['Chromosome']) & (snvs['Location'] == row['Location'])).any()
    else None, axis=1)
comparison

,Unnamed: 0,Chromosome,Genes,Location,Reference Base,Altered Base,numeric,Literature,Drugs,Association,More Details,Dataset,Check Result,Alter Match
0,206,10,ABCC2,99861014,C,G,1,PMID:18294295,docetaxel,Allele G is associated with increased risk of ...,Study genotyped 84 patients from BioBank Japan...,Core,,None
1,135,10,ABCC2,99852563,C,T,1,PMID:27180762,vincristine,Allele T is associated with decreased likeliho...,when comparing zero neurotoxicity vs grades 1-...,Core,,None
2,34,10,ABCC2,99843765,T,C,1,PMID:30100615,rosuvastatin,Allele C is associated with decreased exposure...,NaN,Core,,None
3,46,10,ABCC2,99804028,C,T,1,PMID:30100615,rosuvastatin,Allele T is associated with decreased exposure...,NaN,Core,,None
4,37,10,ABCC2,99804266,C,T,0,PMID:21449672,antiepileptics,Allele C is not associated with resistance to ...,Epilepsy patients on antiepileptic drug (AED) ...,Core,T,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
364,9,4,SLC2A9,9961141,T,C,0,PMCID:PMC5611711,furosemide,Allele C is not associated with response to fu...,There was no difference in either the absolute...,Others,,None
365,10,4,SLC2A9,9920543,C,T,1,PMCID:PMC2779583,NaN,Allele T is associated with decreased serum ur...,"The first part of this study was a GWAS, the f...",Others,T,True
366,5,8,DPYS,104451462,A,G,0,PMCID:PMC3694243,capecitabine; fluorouracil,Allele A is not associated with risk of Drug T...,No significant differences in occurrence of gr...,Others,,None
367,1,8,DPYS,104466921,A,G,1,PMID:26244261,fluorouracil,Allele G is associated with increased likeliho...,This was a trend in the discovery cohort but s...,Others,,None
368,6,8,DPYS,104424265,C,T,0,PMID:26244261,fluorouracil,Allele T is associated with increased likeliho...,This novel rare allele was found in an individ...,Others,,None

In [ ]:
comparison.to_csv('/content/gdrive/My Drive/Colab Notebooks/ADME Project/comparison_results.csv', index=False)

In [ ]:
#Check code
# Create the "Comparison" dataset
comparison_data = {
    'Gene': ['ABC', 'DEF', 'GHI'],
    'Location': [10, 20, 30]
}
comparison = pd.DataFrame(comparison_data)
comparison

  Gene  Location
0  ABC        10
1  DEF        20
2  GHI        30

In [ ]:
# Create the "337SNVs" dataset
snvs_data = {
    'Gene': ['ABC', 'DEF', 'XYZ'],
    'Location': [10, 20, 40],
    'Alter': ['A', 'B', 'C']
}
snvs = pd.DataFrame(snvs_data)
snvs

  Gene  Location Alter
0  ABC        10     A
1  DEF        20     B
2  XYZ        40     C

In [ ]:
# Add a column to store the check result
comparison['Check Result'] = comparison.apply(lambda row: snvs.loc[
    (snvs['Gene'] == row['Gene']) & (snvs['Location'] == row['Location']), 'Alter'].values[0]
    if ((snvs['Gene'] == row['Gene']) & (snvs['Location'] == row['Location'])).any()
    else '', axis=1)

# Print the resulting "Comparison" dataset
comparison

  Gene  Location Check Result
0  ABC        10            A
1  DEF        20            B
2  GHI        30

In [ ]:
comparison['Alter Match'] = comparison.apply(lambda row: snvs.loc[
    (snvs['Gene'] == row['Gene']) & (snvs['Location'] == row['Location']), 'Alter'].values[0] == row['Check Result']
    if ((snvs['Gene'] == row['Gene']) & (snvs['Location'] == row['Location'])).any()
    else None, axis=1)
comparison

  Gene  Location Check Result Alter Match
0  ABC        10            A        True
1  DEF        20            B        True
2  GHI        30                     None