<a href="https://colab.research.google.com/github/katha815/ADME-Classifier/blob/main/Dataset_Expansion5_autoUnlisted21.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive')
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

Mounted at /content/gdrive

In [ ]:
# Data preparation (Trial)

# List of TSV file paths
file_paths = ['/content/gdrive/My Drive/Colab Notebooks/ADME Project/ABCB1.tsv',
         '/content/gdrive/My Drive/Colab Notebooks/ADME Project/ABCG2.tsv',
         '/content/gdrive/My Drive/Colab Notebooks/ADME Project/CYP1A1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/CYP2A6.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/CYP2B6.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/CYP2E1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/CYP3A5.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/DPYD.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/GSTM1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/GSTP1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/GDTT1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/NAT2.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/SLC15A2.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/SLC22A1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/SLC22A6.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/SLCO1B3.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/SULT1A1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/UGT1A1.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/UGT2B15.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/UGT2B17.tsv',
        '/content/gdrive/My Drive/Colab Notebooks/ADME Project/UGT2B7.tsv']

# Create an empty list to store DataFrames
dfs = []

# Read each TSV file and append its DataFrame to the list
for file_path in file_paths:
    try:
        df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
        dfs.append(df)
    except pd.errors.ParserError:
        print(f"Error reading file: {file_path}")

# Concatenate the DataFrames into a single DataFrame
comb_df = pd.concat(dfs, ignore_index=True)

# Save the combined DataFrame as a CSV file
comb_df.to_csv('/content/gdrive/My Drive/Colab Notebooks/ADME Project/unlisted21_auto.csv', index=False)

<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
<ipython-input-82-b23c12e0001c>:32: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version. Use on_bad_lines in the future.


  df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)

Results are reliable: same data size with manual version!

In [ ]:
Core_genes = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/Core ADME Genes.csv")

In [ ]:
Core_genes['Gene'][0]
gene_name = Core_genes['Gene'][0]
gene_name

'ABCB1'

In [ ]:
# Data preparation (real run)
file_paths = []

# List of TSV file paths
for i in range(len(Core_genes['Gene'])):
  if Core_genes['Listed?'][i]==1:
    gene_name = Core_genes['Gene'][i]
    file_paths.append(f'/content/gdrive/My Drive/Colab Notebooks/ADME Project/{gene_name}.tsv')

# Create an empty list to store DataFrames
dfs = []

# Read each TSV file and append its DataFrame to the list
for file_path in file_paths:
    try:
        df = pd.read_csv(file_path, sep='\t', error_bad_lines=False)
        dfs.append(df)
    except pd.errors.ParserError:
        print(f"Error reading file: {file_path}")

# Concatenate the DataFrames into a single DataFrame
raw_df = pd.concat(dfs, ignore_index=True)

# Save the combined DataFrame as a CSV file
raw_df.to_csv('/content/gdrive/My Drive/Colab Notebooks/ADME Project/listedCore_auto.csv', index=False)

NameError: ignored

In [ ]:
# Ref/Alter rows creation (Trial)
df = pd.DataFrame({'Alleles': ['Allele Aasdasd', 'Allele C T', 'allele A G', 'sadasd']})

# Define the search patterns and corresponding replacement values
patterns = ['Allele A ', 'Allele C ', 'Allele G ', 'Allele T ']
patterns2 = ['allele A', 'allele C', 'allele G', 'allele T']
replacements = ['A', 'C', 'G', 'T']

# Create the two new columns using the search patterns and replacements
df['New_Column_1'] = df['Alleles'].apply(lambda x: next((replacements[i] for i, pattern in enumerate(patterns) if pattern in x), np.nan))
df['New_Column_2'] = df['Alleles'].apply(lambda x: next((replacements[i] for i, pattern2 in enumerate(patterns2) if pattern2 in x), np.nan))

# Display the resulting DataFrame
df

          Alleles New_Column_1 New_Column_2
0  Allele Aasdasd          NaN          NaN
1      Allele C T            C          NaN
2      allele A G          NaN            A
3          sadasd          NaN          NaN

In [ ]:
# Ref/Alter rows creation (Real-run)
data = comb_df
#raw_df

# Define the search patterns and corresponding replacement values
patterns = ['Allele A ', 'Allele C ', 'Allele G ', 'Allele T ']
patterns2 = ['allele A', 'allele C', 'allele G', 'allele T']
replacements = ['A', 'C', 'G', 'T']

# Create the two new columns using the search patterns and replacements
data['Alter'] = data['Association'].apply(lambda x: next((replacements[i] for i, pattern in enumerate(patterns) if pattern in x), np.nan))
data['Ref'] = data['Association'].apply(lambda x: next((replacements[i] for i, pattern2 in enumerate(patterns2) if pattern2 in x), np.nan))

data

,PharmGKB ID,Variant,Literature,Drugs,Association,Significance,P-Value,# of Cases,# of Controls,Biogeographical Groups,Phenotype Categories,Pediatric,More Details,Genes,Alter,Ref,numeric
0,1183491722,rs1045642,PMID:23900887,tacrolimus,Genotype GG is not associated with risk of tra...,no,= 0.70,88.0,NaN,European,Efficacy,False,In those with DONOR LIVERS with these genotype...,ABCB1,NaN,NaN,0.0
1,1451335298,rs4728709,PMID:33378980,olanzapine,Allele G is not associated with exposure to ol...,no,> 0.05,80.0,NaN,"Multiple groups, ""36 Caucasians, 42 Latin-Amer...",Metabolism/PK,False,No significant difference in a number of pharm...,ABCB1,G,A,0.0
2,1183491726,rs1045642,PMID:22725663,talinolol,Genotype AA is associated with increased clear...,yes,= 0.028,18.0,NaN,East Asian,Metabolism/PK,False,Subjects with the AA genotype had increased or...,ABCB1,NaN,NaN,1.0
3,1451335303,rs7787082,PMID:33378980,olanzapine,Allele A is not associated with exposure to ol...,no,> 0.05,80.0,NaN,"Multiple groups, ""36 Caucasians, 42 Latin-Amer...",Metabolism/PK,False,No significant difference in a number of pharm...,ABCB1,A,G,0.0
4,1184349841,rs1045642,PMCID:PMC4104276,clopidogrel,Allele A is not associated with increased risk...,no,= 0.046,1632.0,NaN,European,Toxicity,False,NaN,ABCB1,A,G,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5261,1448098981,rs62298861,PMID:26213157,lamotrigine,Genotype AA is not associated with increased c...,no,= 0.278,140.0,NaN,East Asian,Metabolism/PK,False,The concentration was measured as lamotrigine ...,UGT2B7,NaN,NaN,0.0
5262,827812768,rs28365062,PMID:21806385,valproic acid,Genotype GG is not associated with increased d...,no,NaN,162.0,NaN,East Asian,"Dosage,Metabolism/PK",False,Variant described as UGT2B7 735A>G (rsID not r...,UGT2B7,NaN,NaN,0.0
5263,1452121460,rs73823859,PMID:37248824,codeine; morphine; tramadol,Allele A is associated with increased Pain whe...,yes,= 0.0454,106.0,NaN,Sub-Saharan African,Efficacy,True,"""However, UGT2B7 rs73823859 showed a statistic...",UGT2B7,A,G,1.0
5264,1448531887,rs28365063,PMID:28063968,morphine,Allele G is not associated with exposure to mo...,no,= 0.51,22.0,NaN,European,Metabolism/PK,False,"Measures assessed were AUC, transit compartmen...",UGT2B7,G,A,0.0
5265,1448531882,rs7438135,PMID:28063968,morphine,Allele G is not associated with exposure to mo...,no,= 0.32,22.0,NaN,European,Metabolism/PK,False,"Measures assessed were AUC, transit compartmen...",UGT2B7,G,A,0.0

## Arthitecture and Principal:
This code should be able to rearrange data downloaded from PharmGKB with only two added columns ("Alter" and "Ref"), and produces a usable datasheet with chormosome, location, alter, ref and a label of pharmacogenetic significance.

In [ ]:
# Load data
#data = pd.read_csv("/content/gdrive/My Drive/Colab Notebooks/ADME Project/listed_core_o.csv")

In [ ]:
# Only select SNPs which pharmacogenetic significance is known

data['numeric'] = data['Significance'].map({'yes': 1, 'no': 0})
data_dropped = data.dropna(subset=['numeric','Alter'])

In [ ]:
# Sort with variant, alternative base and significant label
#This sorted data set can refered later for certain variant location
#as it includes all related literature.

data_sorted = data_dropped.sort_values(['Variant','Alter','Significance'])

In [ ]:
# If for the same alternative base and same variant location, there are both significant report and non-siginificant report,
#delete the later.

data_unique = data_sorted.drop_duplicates(subset=['Variant', 'Alter'], keep='last')

In [ ]:
import requests

# Create empty lists to store the genomic information
chromosomes = []
locations = []
reference_bases = []

# Base URL for Ensembl REST API
base_url = 'https://rest.ensembl.org'

# Iterate over rsIDs
for rsID in data_unique['Variant']:
    # Construct the API endpoint URL
    endpoint = f'{base_url}/variation/human/{rsID}?phenotypes=1'

    # Send GET request to the API
    response = requests.get(endpoint, headers={'Content-Type': 'application/json'})

    # Check if the request was successful
    if response.status_code == 200:
        # Extract relevant information from the response
        data = response.json()
        chromosome = data['mappings'][0]['seq_region_name']
        location = data['mappings'][0]['start']
        reference_base = data['mappings'][0]['allele_string'].split('/')[0]

        # Append the genomic information to the respective lists
        chromosomes.append(chromosome)
        locations.append(location)
        reference_bases.append(reference_base)
    else:
        # If there was an error, append None to the lists
        chromosomes.append(None)
        locations.append(None)
        reference_bases.append(None)

# Create a new DataFrame with the genomic information
search_df = pd.DataFrame({
    'Chromosome': chromosomes,
    'Location': locations,
    'Reference Base': reference_bases
})

In [ ]:
# Combine the search results with orginal dataset
search_df.set_index(data_unique.index, inplace=True)
combined_df = data_unique.join(search_df)
#combined_df.to_csv('/content/gdrive/My Drive/Colab Notebooks/ADME Project/Unlisted_auto_v1.csv')

*Trim the code with GRCh38 setting.
error soruce: https://rest.ensembl.org/vep/human/region/22:24034135:24034135/A
Checked Unlisted_o, further debugging:
https://rest.ensembl.org/variation/human/rs4630?content-type=application/json

In [ ]:
# Filter duplicates

combined_df['Combination'] = combined_df[['Alter', 'Ref']].apply(lambda x: ''.join(sorted(x.values.astype(str))), axis=1)
# Drop rows where Column1 and Combination values are the same, and Column4 is 'no'
filterd_df = combined_df.dropna(subset=['Chromosome','Location','Reference Base'])
filterd_df = filterd_df[~((combined_df.duplicated(subset=['Location', 'Combination']) & (combined_df['numeric'] == 0)) |
      ((combined_df['numeric'] == 1) & combined_df.duplicated(subset=['Location', 'Combination']) & (combined_df.groupby('Location')['numeric'].transform('max') == 1)))]

In [ ]:
# Finalizing
#"Pediatric" deleted due to irrelavance
final1 = filterd_df[['Chromosome','Genes','Location','Reference Base','Alter','Combination','numeric','Literature','Drugs','Association','More Details']]

In [ ]:
# Filter again
#1)Combination Combination - Reference Base
#2)Delete nan Combination
#3)Change the rest Combination to "True Alter"
filtered2 = final1
filtered2['Combination'] = final1.apply(lambda row: str(row['Combination']).replace(str(row['Reference Base']), ''), axis=1)

<ipython-input-101-4d14096c7fa8>:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered2['Combination'] = final1.apply(lambda row: str(row['Combination']).replace(str(row['Reference Base']), ''), axis=1)

In [ ]:
data_dropped2 = filtered2[~(filtered2['Combination'] == 'nan')]

In [ ]:
# Final 2: Calculate True Alter
final2 = data_dropped2
final2['Combination'] = data_dropped2.apply(lambda row: row['Alter'] if str(row['Alter']) != str(row['Reference Base']) else str(row['Combination']), axis=1)

<ipython-input-103-80a9026e924b>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final2['Combination'] = data_dropped2.apply(lambda row: row['Alter'] if str(row['Alter']) != str(row['Reference Base']) else str(row['Combination']), axis=1)

In [ ]:
# Final 3: Delete irrelevant column
final3 = final2.drop(columns='Alter')
final3 = final3.rename(columns={'Combination': 'Altered Base'})
final3 = final3[~(final3['Altered Base'] == None)]
final3

,Chromosome,Genes,Location,Reference Base,Altered Base,numeric,Literature,Drugs,Association,More Details
5148,4,UGT2B7,69112090,T,C,0.0,PMID:30920410,morphine,Allele C is not associated with metabolism of ...,Variant was potentially associated with morphi...
1603,4,ABCG2,88169725,T,C,0.0,PMID:30924126,allopurinol,Allele T is associated with decreased response...,Response to allopurinol was determined by whet...
5108,4,UGT2B7,69105219,A,C,0.0,PMCID:PMC5521342,fentanyl,Allele A is not associated with dose of fentan...,There was no significant difference in 24 hour...
4231,22,GSTT1,23898914,C,T,1.0,PMCID:PMC3564008,NaN,Allele T is associated with increased transcri...,NaN
973,7,ABCB1,87535576,T,A,0.0,PMID:26421491,carbamazepine,Allele A is not associated with concentrations...,NaN
...,...,...,...,...,...,...,...,...,...,...
1719,19,CYP2A6,40848591,C,A,0.0,PMID:23172109,efavirenz,Allele A is not associated with metabolism of ...,No association was seen between this polymorph...
4791,2,UGT1A1,233772999,G,C,1.0,PMID:25151207,atazanavir; ritonavir,Allele G is associated with increased risk of ...,The authors compared the frequencies of the G ...
649,7,ABCB1,87560614,T,G,0.0,PMID:30713339,imatinib,Allele T is not associated with risk of Drug T...,No significant association between genotype an...
4813,2,UGT1A1,233759924,C,T,0.0,PMCID:PMC5508045,warfarin,Allele C is not associated with dose of warfar...,NaN
587,7,ABCB1,87600124,T,C,1.0,PMCID:PMC5354739,methotrexate,Allele C is associated with increased concentr...,Concentrations refers to area under the concen...

In [ ]:
np.shape(final3)

(353, 10)

In [ ]:
final4 = final3.sort_values(['Chromosome', 'Genes'])
final4

,Chromosome,Genes,Location,Reference Base,Altered Base,numeric,Literature,Drugs,Association,More Details
3622,1,DPYD,97549600,T,C,1.0,PMCID:PMC4012613,fluorouracil,Allele C is associated with decreased activity...,Functional study. The C allele was associated ...
3663,1,DPYD,97305279,G,A,1.0,PMCID:PMC4012613,fluorouracil,Allele A is associated with decreased activity...,Functional study. The A allele was associated ...
3752,1,DPYD,97078987,G,T,1.0,PMCID:PMC5309195,NaN,Allele T is associated with decreased catalyti...,This variant is also called p.P1023S and is fo...
3563,1,DPYD,97699474,T,C,1.0,PMCID:PMC4012613,fluorouracil,Allele C is associated with decreased activity...,Functional study. The C allele was associated ...
3974,1,DPYD,97593438,A,C,1.0,PMID:19530960,capecitabine; fluorouracil,Allele C is associated with increased severity...,The C allele was more common in those with Gra...
...,...,...,...,...,...,...,...,...,...,...
4452,8,NAT2,18390758,G,C,1.0,PMID:20602614,aspirin,Allele C is associated with increased risk of ...,The C allele was found at a higher frequency i...
4301,8,NAT2,18400616,A,T,0.0,PMCID:PMC3619396,sulfamethoxazole / trimethoprim,Allele T is not associated with increased risk...,Minor allele frequencies were compared between...
4404,8,NAT2,18390208,T,A,1.0,PMID:19891553,ethambutol; isoniazid; pyrazinamide; rifampin,Allele A is associated with increased risk of ...,The frequency of the A allele was significantl...
4327,8,NAT2,18390403,A,G,0.0,PMID:19891553,ethambutol; isoniazid; pyrazinamide; rifampin,Allele G is not associated with risk of Hepati...,The frequency of the G allele or genotype freq...
4217,CHR_HSCHR22_1_CTG7,GSTT1,24034135,G,A,0.0,PMID:19504558,dexamethasone; diphenhydramine; paclitaxel; ra...,Allele G is not associated with overall surviv...,"Although not significant alone, when looked at..."

In [ ]:
final4.to_csv('/content/gdrive/My Drive/Colab Notebooks/ADME Project/Unlisted_auto.csv')